### PR TITLE
Namespace "notify" and create "docker" class

### PR DESCRIPTION
**Pull request by surminus**
This PR does two things:

## Break out "notify" into it's own namespace 

This allows loading the useful notify namespace without having to load the "defaults" which loads things we may not want. It moves it away from the "deploy" namespace into it's very own namespace.

## Create docker class

This creates a docker class and adds a conditional around loading this class for the [release](https://github.com/alphagov/release) app based upon running that deploy task.

### CODE REVIEW

**Comment by tijmenb** [comment]
I think it's not necessary to rename the task. You can "open up" namespaces / declare it multiple times, so putting `deploy:notify` into a separate file is possibly enough to achieve what you want.

**Comment by surminus** [comment]
I specifically renamed it to make it clearer as it's own "thing", but I can re-do it so the change touches fewer files.

**Comment by tijmenb** [comment]
Okido, in that case it looks good!

**Comment by surminus** [comment]
Great, I've squashed that into better commits.

**Pull request merged**
