### PR TITLE
Upgrade Ruby to 2.7.2

### PR DESCRIPTION
**Pull request by pixeltrix**
Upgrade Ruby to 2.7.2, see commits for individual changes.

### CODE REVIEW

**Comment by thomasleese** [comment]
Seems like there's a different error this time :(

```
07:58:16 + exec bundle exec cap app:migrate_and_hard_restart
07:58:17 [DEPRECATED] The Bundler task for Capistrano. Please use https://github.com/capistrano/bundler
07:58:17 [DEPRECATED] Bundler no longer integrates with Capistrano, but Capistrano provides its own integration with Bundler via the capistrano-bundler gem. Use it instead.
07:58:17     triggering start callbacks for `app:migrate_and_hard_restart'
07:58:17   * executing `deploy:set_servers'
07:58:18  ** set_servers: deploying to backend => ip-10-1-4-11.eu-west-1.compute.internal (primary), ip-10-1-5-36.eu-west-1.compute.internal
07:58:18     triggering after callbacks for `deploy:set_servers'
07:58:18   * executing `deploy:setup'
07:58:18   * executing "mkdir -p /data/apps/content-publisher /data/apps/content-publisher/releases /data/apps/content-publisher/shared /data/apps/content-publisher/shared/system /data/apps/content-publisher/shared/log /data/apps/content-publisher/shared/pids"
07:58:18     servers: ["ip-10-1-4-11.eu-west-1.compute.internal", "ip-10-1-5-36.eu-west-1.compute.internal"]
07:58:18 connection failed for: ip-10-1-5-36.eu-west-1.compute.internal (ArgumentError: invalid option(s): strict_host_key_checking), ip-10-1-4-11.eu-west-1.compute.internal (ArgumentError: invalid option(s): strict_host_key_checking)
```

**Comment by pixeltrix** [comment]
Investigating but that option isn't set anywhere in this repo 🤔

**Comment by thomasleese** [comment]
There still seems to be a problem with this unfortunately, I've attached the logs from Ruby 2.6 vs 2.7: https://gist.github.com/thomasleese/708a6cd7962b3ce15667db38a98c1ec8

**Comment by pixeltrix** [comment]
Looking at this line:

https://gist.github.com/thomasleese/708a6cd7962b3ce15667db38a98c1ec8#file-ruby-2-6-L291

```
12:37:22   * executing "chmod -R g+w /data/apps/collections/releases/20201020123721"
```

vs. this line:

https://gist.github.com/thomasleese/708a6cd7962b3ce15667db38a98c1ec8#file-ruby-2-7-L307

```
12:51:12   * executing "chmod -R -- g+w /data/apps/collections/releases/20201020125112 && rm -rf -- /data/apps/collections/releases/20201020125112/public/system && mkdir -p -- /data/apps/collections/releases/20201020125112/public/ && ln -s -- /data/apps/collections/shared/system /data/apps/collections/releases/20201020125112/public/system && rm -rf -- /data/apps/collections/releases/20201020125112/log && ln -s -- /data/apps/collections/shared/log /data/apps/collections/releases/20201020125112/log && rm -rf -- /data/apps/collections/releases/20201020125112/tmp/pids && mkdir -p -- /data/apps/collections/releases/20201020125112/tmp/ && ln -s -- /data/apps/collections/shared/pids /data/apps/collections/releases/20201020125112/tmp/pids"
```

It appears that `deploy:assets:symlink` stage is different in the later version of Capistrano and is deleting a shared directory that contains a manifest because it then errors out shortly after with the following:

```
12:51:36   * executing "ls -1 /data/apps/collections/shared/assets/manifest* | wc -l"
12:51:36     servers: ["ip-10-1-5-213.eu-west-1.compute.internal"]
12:51:36     [ip-10-1-5-213.eu-west-1.compute.internal] executing command
12:51:36 [err :: ip-10-1-5-213.eu-west-1.compute.internal] ls: cannot access /data/apps/collections/shared/assets/manifest*
12:51:36 [err :: ip-10-1-5-213.eu-west-1.compute.internal] : No such file or directory
```

Investigating why there's a difference at that stage.

**Comment by pixeltrix** [comment]
Looks like there were some changes in later versions of Capistrano 2.x to handle the Rails 3 to 4 upgrade around assets where Sprockets went from 2.x to 3.x. These seem to be failing so rather than spend time diagnosing what's up on the server I've rolled back Capistrano to 2.13.5 which just runs `rake assets:precompile` and doesn't do anything else.

**Comment by thomasleese** [comment]
The latest build passed, so I think we're good to merge this!

**Review by thomasleese — APPROVED** [review]

**Pull request merged**
