### PR TITLE
Remove all references to performanceplatform-admin

### PR DESCRIPTION
**Pull request by pcraig3**
[Performanceplatform-admin has been removed from `govuk-puppet`](https://github.com/alphagov/govuk-puppet/pull/6719), so we can get rid of this as well.

### CODE REVIEW

**Comment by cbaines** [comment]
Could this be removed at some point as well? https://github.com/alphagov/govuk-app-deployment/tree/master/performanceplatform-big-screen-view

**Comment by pcraig3** [comment]
Totally, man.

**Comment by pcraig3** [comment]
There's actually another PR open right now -> #207

**Comment by cbaines** [comment]
> There's actually another PR open right now -> #207

Great, I've approved 👍

**Pull request merged**
