### PR TITLE
Remove email campaign

### PR DESCRIPTION
**Pull request by surminus**

### CODE REVIEW

**Comment by alexmuller** [comment]
:+1:

share-sale-publisher can also go.

**Comment by surminus** [comment]
@alexmuller removed share-sale-publisher too! Can you approve?

**Comment by alexmuller** [comment]
There's a `Capfile` in `share-sale-publisher/` too, sorry!

**Comment by alexmuller** [comment]
I removed the additional file.

**Comment by surminus** [comment]
Thanks! Shall we merge?

**Pull request merged**
